/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthIdentitiesTab: typeof import('./src/components/admin/AuthIdentitiesTab.vue')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LightweightChart: typeof import('./src/components/LightweightChart.vue')['default']
    MarkerModal: typeof import('./src/components/MarkerModal.vue')['default']
    Message: typeof import('primevue/message')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    Password: typeof import('primevue/password')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RolesTab: typeof import('./src/components/admin/RolesTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SpacesTab: typeof import('./src/components/admin/SpacesTab.vue')['default']
    SpaceSwitcher: typeof import('./src/components/SpaceSwitcher.vue')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    TenantSwitcher: typeof import('./src/components/TenantSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    UserAuthIdentitiesTab: typeof import('./src/components/admin/UserAuthIdentitiesTab.vue')['default']
    UserManagementTab: typeof import('./src/components/admin/UserManagementTab.vue')['default']
    UserProfileTab: typeof import('./src/components/admin/UserProfileTab.vue')['default']
    UserSpaceMembershipsTab: typeof import('./src/components/admin/UserSpaceMembershipsTab.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
